---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: post-endpoint
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: reddit
      component: post
  endpoints:
    - port: "reddit-test-post"
