---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  storageClassName: yc-network-hdd
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  csi:
    driver: disk-csi-driver.mks.ycloud.io
    fsType: ext4
    volumeHandle: {{.Values.volumeHandle }}
