FROM grafana/grafana:5.0.0

COPY prometheus_data_source.yml /etc/grafana/provisioning/datasources/prometheus_data_source.yml
COPY dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yml
COPY dashboards /etc/dashboards
