---
- name: install container runtime
  hosts: all
  tasks:
    - name: load modules at bootup
      become: true
      copy:
        src: ../files/crio.conf
        dest: /etc/modules-load.d/crio.conf

    - name: load necessary modules
      become: true
      modprobe:
        name: '{{ item }}'
        state: present
      loop:
        - br_netfilter
        - overlay

    - name: configure iptables to see bridged traffic
      become: true
      sysctl:
        name: '{{ item }}'
        value: '1'
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-ip6tables

    - name: install GPG key
      become: true
      apt_key:
        url: '{{ item.url }}'
        keyring: '{{ item.keyring }}'
        state: present
      loop:
        - {
          keyring: '/etc/apt/trusted.gpg.d/libcontainers.gpg',
          url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/Release.key'
        }
        - {
          keyring: '/etc/apt/trusted.gpg.d/libcontainers-cri-o.gpg',
          url: 'https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.19/xUbuntu_18.04/Release.key'
        }

    - name: add apt repositories
      become: true
      apt_repository:
        repo: '{{ item.repo }}'
        filename: '{{ item.filename }}'
        state: present
      loop:
        - {
          filename: '/etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list',
          repo: 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /'
        }
        - {
          filename: '/etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.19.list',
          repo: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.19/xUbuntu_18.04/ /'
        }

    - name: install runtime
      become: true
      apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      loop:
        - cri-o
        - cri-o-runc

    - name: restart services
      become: true
      systemd:
        daemon-reload: true
        name: crio
        enabled: true

    - name: conifg cri-o
      become: true
      copy:
        src: ../files/02-cgroup-manager.conf
        dest: /etc/crio/crio.conf.d/02-cgroup-manager.conf
