comment:
  image:
    repository: dmnbars/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: dmnbars/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: dmnbars/ui
    tag: latest
  service:
    externalPort: 9292

mongodb:
  auth:
    enabled: false
